seo-bundle:
  description: |
      It provides a solution to make content bundles
      aware for Search Engine Optimisation (SEO).
  branches:
    master:
      minimum_stability: dev
      docs_path: 'bundles/seo'
      test_kernel: 'Symfony\Cmf\Bundle\SeoBundle\Tests\Fixtures\App\Kernel'
      deprecation_warnings: 0
      php: ['7.1']
      make_tasks:
        unit_tests: ~
        functional_tests_phpcr: ~
        functional_tests_orm: ~
        test_installation: ~
      versions:
        symfony: ['2.8.*',  '3.3.*', '3.4.*', '4.0.*']
core-bundle:
  description: |
      The CoreBundle for the Symfony content management framework provides common functionality,
      helpers and utilities for the other CMF bundles. The major features are a publish workflow,
      a twig extension and php templating helper to walk PHPCR-ODM trees and support for optional translated content.
  branches:
    master:
      minimum_stability: dev
      docs_path: 'bundles/core'
      test_kernel: Symfony\Cmf\Bundle\CoreBundle\Tests\Fixtures\App\Kernel
      deprecation_warnings: 0
      php: ['7.1']
      make_tasks:
        unit_tests: ~
        functional_tests_phpcr: ~
        test_installation: ~
      versions:
        symfony: ['2.8.*', '3.3.*', '3.4.*', '4.0.*']
block-bundle:
  description: |
      The BlockBundle provides integration with
      [SonataBlockBundle](https://github.com/sonata-project/SonataBlockBundle).
      It is used to manage fragments of content, so-called blocks, that are persisted
      in a database and can be incorporated into any page layout. The BlockBundle also
      provides a few commonly used standard blocks, including the ability to edit them.
  branches:
    master:
      minimum_stability: dev
      docs_path: 'bundles/block'
      test_kernel: Symfony\Cmf\Bundle\BlockBundle\Tests\Fixtures\App\Kernel
      deprecation_warnings: 0
      php: ['7.1']
      make_tasks:
        unit_tests: ~
        functional_tests_phpcr: ~
        test_installation: ~
      versions:
        symfony: ['2.8.*', '3.3.*', '3.4.*', '4.0.*']
menu-bundle:
  description: |
      The MenuBundle provides menus from a doctrine object manager with the help of KnpMenuBundle.
  branches:
    master:
      minimum_stability: dev
      docs_path: 'bundles/menu'
      deprecation_warnings: 0
      test_kernel: Symfony\Cmf\Bundle\MenuBundle\Tests\Fixtures\App\Kernel
      php: ['7.1']
      make_tasks:
        unit_tests: ~
        functional_tests_phpcr: ~
        test_installation: ~
      versions:
        symfony: ['2.8.*', '3.3.*', '3.4.*', '4.0.*']
routing-bundle:
  description: |
      The RoutingBundle enables the
      [CMF Routing component](https://github.com/symfony-cmf/Routing)
      as a Symfony bundle. It provides route documents for Doctrine PHPCR-ODM and a
      controller for redirection routes.
  branches:
    master:
      minimum_stability: dev
      docs_path: 'bundles/routing'
      deprecation_warnings: 0
      test_kernel: Symfony\Cmf\Bundle\RoutingBundle\Tests\Fixtures\App\Kernel
      php: ['7.1']
      make_tasks:
        unit_tests: ~
        functional_tests_phpcr: ~
        functional_tests_orm: ~
        test_installation: ~
      versions:
        symfony: ['2.8.*', '3.3.*', '3.4.*', '4.0.*', '4.0.*']
routing:
  description: |
      The Symfony CMF Routing component extends the Symfony routing component with additional features:

       * A ChainRouter to run several routers in parallel
       * A DynamicRouter that can load routes from any database and can generate
         additional information in the route match.

      The CMF Routing component does not need the Symfony full stack framework. It is
      also useful in applications not using the full Symfony framework.

      For the best integration into the Symfony full stack framework, it is
      recommended to use the [RoutingBundle](https://github.com/symfony-cmf/RoutingBundle)
      when building Symfony full stack applications.
  branches:
    master:
      minimum_stability: dev
      docs_path: 'components/routing'
      deprecation_warnings: 0
      php: ['7.1']
      make_tasks:
        unit_tests: ~
      versions:
        symfony: ['2.8.*', '3.3.*', '3.4.*', '4.0.*',]
routing-auto:
  description: |
      This component automatically creates and manages routes for configured persisted document classes.
      This library contains all implementation agnostic code.
  branches:
    master:
      minimum_stability: dev
      docs_path: 'components/routing'
      deprecation_warnings: 0
      php: ['7.1']
      make_tasks:
        unit_tests: ~
      versions:
        symfony: ['2.8.*', '3.3.*', '3.4.*', '4.0.*']
content-bundle:
  description: |
      The ContentBundle provides a document for static content and the controller to render it.
  branches:
    master:
      minimum_stability: dev
      docs_path: 'bundles/routing'
      deprecation_warnings: 0
      test_kernel: Symfony\Cmf\Bundle\ContentBundle\Tests\Fixtures\App\Kernel
      php: ['7.1']
      make_tasks:
        unit_tests: ~
        functional_tests_phpcr: ~
        test_installation: ~
      versions:
        symfony: ['2.8.*', '3.3.*', '3.4.*', '4.0.*']
routing-auto-bundle:
  description: |
      This bundle automatically creates and manages routes for configured persisted document classes.
  branches:
    master:
      minimum_stability: dev
      docs_path: 'bundles/routing-auto-bundle'
      test_kernel: Symfony\Cmf\Bundle\RoutingAutoBundle\Tests\Fixtures\App\Kernel
      deprecation_warnings: 0
      php: ['7.1']
      make_tasks:
        unit_tests: ~
        functional_tests_phpcr: ~
        test_installation: ~
      versions:
        symfony: ['2.8.*', '3.3.*', '3.4.*', '4.0.*']
resource-rest-bundle:
  description: |
      This Bundle provides a REST API to Puli resources as provided by the CmfResource component.

      #### Running Behat

      1. Run web server:
      ```
      KERNEL_CLASS="Symfony\Cmf\Bundle\ResourceRestBundle\Tests\Fixtures\App\Kernel" ./vendor/symfony-cmf/testing/bin/console server:run -d vendor/symfony-cmf/testing/resources/web/ 8000
      ```
      2. Run the behat tests:
      ```
      KERNEL_CLASS="Symfony\Cmf\Bundle\ResourceRestBundle\Tests\Fixtures\App\Kernel" ./vendor/bin/behat
      ```

  branches:
    master:
      minimum_stability: dev
      docs_path: 'bundles/resource-rest'
      deprecation_warnings: 0
      test_kernel: Symfony\Cmf\Bundle\ResourceRestBundle\Tests\Fixtures\App\Kernel
      php: ['7.1']
      make_tasks:
        unit_tests: ~
        test_installation: ~
      versions:
        symfony: ['2.8.*', '3.3.*', '3.4.*', '4.0.*']
resource-bundle:
  description: |
      This bundle provides *object* resource location services based on Puli.

      Examples:

      - **Static document path mapping**: Map the path `/routes` to `/cms/routes`
      - **Dynamic document resolution**: Map the path `/routes` to `/cms/<current site>/routes`.
      - **Access documents at a static location**: Map `/role/menu/main` to `/cms/menus/main-menu`.

      The first example could use the existing CMF base route configuration to
      resolve paths.

      The benefit of the above two examples would be most strongly felt in
      association with another component which would provide a context for the
      document resource resolution.

      For example, a `Site` which is matched against the incoming hostname would
      provide the context with which to resolve the documents.

  branches:
    master:
      minimum_stability: dev
      docs_path: 'bundles/resource-rest'
      deprecation_warnings: 0
      test_kernel: Symfony\Cmf\Bundle\ResourceBundle\Tests\Fixtures\App\Kernel
      php: ['7.1']
      make_tasks:
        unit_tests: ~
        functional_tests_phpcr: ~
        test_installation: ~
      versions:
        symfony: ['2.8.*', '3.3.*', '3.4.*', '4.0.*']
sonata-phpcr-admin-integration-bundle:
  description: ""
  branches:
    master:
      minimum_stability: dev
      docs_path: 'bundles/sonata-phpcr-admin-integration-bundle'
      test_kernel: Symfony\Cmf\Bundle\SonataPhpcrAdminIntegrationBundle\Tests\Fixtures\App\Kernel
      deprecation_warnings: 0
      php: ['7.1']
      make_tasks:
        unit_tests: ~
        functional_tests_phpcr: ~
        test_installation: ~
      versions:
        symfony: ['2.8.*','3.3.*', '3.4.*', '4.0.*']
resource:
  excluded_files:
      - .travis.yml.twig
  description: |
    The Resource component provides PHPCR/ODM integration with Puli.

     > **CAUTION** As Puli is not yet stable, the complete component is marked
     > internal. Backwards compatibility of upcoming 1.x versions is not
     > guaranteed.

  branches:
    master:
      minimum_stability: dev
      docs_path: 'components/resource'
      deprecation_warnings: 0
      php: ['7.1']
      make_tasks:
        unit_tests: ~
testing:
  description: |
    **NOTE**: This is an internal tool and is not intended to be used outside of
    the context of the CMF.

  branches:
    master:
      minimum_stability: dev
      docs_path: 'components/testing'
      deprecation_warnings: 0
      php: ['7.1']
      make_tasks:
        unit_tests: ~
      versions:
        symfony: ['2.8.*', '3.3.*', '3.4.*', '4.0.*']
tree-browser-bundle:
  excluded_files:
      - .travis.yml.twig
  description: |
    The TreeBrowserBundle provides tree navigation for the Content Repository.

  branches:
    master:
      minimum_stability: dev
      docs_path: 'bundle/tree-browser-bundle'
      deprecation_warnings: 0
      php: ['7.1']
      make_tasks:
        unit_tests: ~
        test_installation: ~
      versions:
        symfony: ['2.8.*', '3.3', '3.4.*', '4.0.*']